---
- name: Delete network class on all devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
  vars:
    dp_ip:
      - "10.105.192.32"
      # - "10.105.192.33"
    # To get the list of network classes to delete and rsBWMNetworkSubIndex, you can use the get_network_class module
    delete_networks:
      - {rsBWMNetworkName: "egor_test_net",rsBWMNetworkSubIndex: "0"}
      - {rsBWMNetworkName: "egor_test_net",rsBWMNetworkSubIndex: "1"}
      - {rsBWMNetworkName: "egor_test_net",rsBWMNetworkSubIndex: "2"}
      - {rsBWMNetworkName: "egor_test_net",rsBWMNetworkSubIndex: "3"}

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Delete each network group on all devices
          vars:
            network_device_matrix: "{{ dp_ip | product(delete_networks) | list }}"
          loop: "{{ network_device_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.rsBWMNetworkName }}/{{ item.1.rsBWMNetworkSubIndex }}"
          delete_network_class:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            class_name: "{{ item.1.rsBWMNetworkName }}"
            index: "{{ item.1.rsBWMNetworkSubIndex }}"
      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
